#!/usr/bin/env bash
#
# boot-stack.sh — Bring up the Docker AI stack on every login/reboot
#
# Registered as launchd agent local.ai-stack.boot by start.sh.
# Fires automatically after login. Covers all boot scenarios:
#
#   Normal reboot      → containers exist, docker compose up is a no-op
#   Power loss         → same as above (restart: unless-stopped handled by Docker)
#   After compose down → containers gone, this recreates them
#   After teardown     → DB is wiped, this re-applies the ComfyUI patch
#   Missing override   → regenerates docker-compose.override.yml from .env
#
# Does NOT pull models or bootstrap ComfyUI — run ./start.sh for
# first-time setup or to add models.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

mkdir -p "$SCRIPT_DIR/logs"
LOG="$SCRIPT_DIR/logs/boot-stack.log"

# Under launchd, stdout is already redirected to logs/boot-stack.log via
# StandardOutPath. We write directly to the log file AND stdout so the
# output appears both when run manually and in the launchd log.
# The launchd plist uses /dev/null for StandardOutPath to avoid duplication.
log() {
    local line
    line="$(printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*")"
    printf '%s\n' "$line" >> "$LOG"
    printf '%s\n' "$line"
}

log "=== boot-stack start ==="

# ── Bail if the stack has never been provisioned ─────────────
if [ ! -f .env ]; then
    log "No .env — stack not provisioned yet. Run ./start.sh first."
    exit 1
fi

set -a; source .env; set +a
OLLAMA_MODE="${OLLAMA_MODE:-native}"
OLLAMA_KEEP_ALIVE="${OLLAMA_KEEP_ALIVE:-30s}"
ENABLE_IMAGE_GENERATION="${ENABLE_IMAGE_GENERATION:-true}"
IMAGE_GEN_BACKEND="${IMAGE_GEN_BACKEND:-comfyui}"
COMFYUI_PORT="${COMFYUI_PORT:-8188}"
DRAW_THINGS_PORT="${DRAW_THINGS_PORT:-7860}"
DRAW_THINGS_PROXY_PORT="${DRAW_THINGS_PROXY_PORT:-7861}"
DRAW_THINGS_DEFAULT_MODEL="${DRAW_THINGS_DEFAULT_MODEL:-flux_1_dev_q8p.ckpt}"
WEBUI_PORT="${WEBUI_PORT:-3000}"

# ── Wait for Docker/Colima (up to 120 s) ────────────────────
log "Waiting for Docker..."
for i in $(seq 1 60); do
    if docker info >/dev/null 2>&1; then
        log "Docker ready."
        break
    fi
    if [ "$i" -eq 60 ]; then
        log "ERROR: Docker not available after 120 s — giving up."
        exit 1
    fi
    sleep 2
done

# ── Regenerate override if missing ───────────────────────────
OVERRIDE="docker-compose.override.yml"
if [ ! -f "$OVERRIDE" ]; then
    log "Regenerating $OVERRIDE from .env..."
    {
        echo "# Auto-generated by boot-stack.sh — do not edit manually"
        echo "services:"
        echo "  open-webui:"
        if [ "$OLLAMA_MODE" = "docker" ]; then
            echo "    depends_on:"
            echo "      ollama:"
            echo "        condition: service_healthy"
            echo "    environment:"
        else
            echo "    environment:"
            echo "      - OLLAMA_BASE_URL=http://host.docker.internal:11434"
        fi
        if [ "$ENABLE_IMAGE_GENERATION" = "true" ]; then
            echo "      - ENABLE_IMAGE_GENERATION=true"
            if [ "$IMAGE_GEN_BACKEND" = "drawthings" ]; then
                echo "      - IMAGE_GENERATION_ENGINE=automatic1111"
                echo "      - AUTOMATIC1111_BASE_URL=http://host.docker.internal:${DRAW_THINGS_PROXY_PORT}"
            else
                echo "      - IMAGE_GENERATION_ENGINE=comfyui"
                echo "      - COMFYUI_BASE_URL=http://host.docker.internal:${COMFYUI_PORT}"
                echo "      - IMAGES_EDIT_COMFYUI_BASE_URL=http://host.docker.internal:${COMFYUI_PORT}"
                echo "      - ENABLE_RAG_LOCAL_WEB_FETCH=true"
            fi
        fi
        if [ "$OLLAMA_MODE" = "docker" ]; then
            echo "  ollama-proxy:"
            echo "    depends_on:"
            echo "      ollama:"
            echo "        condition: service_healthy"
        fi
    } > "$OVERRIDE"
    log "Regenerated $OVERRIDE."
fi

# ── Bring up the Docker stack ────────────────────────────────
log "Starting Docker stack..."
if [ "$OLLAMA_MODE" = "docker" ]; then
    docker compose --profile docker up -d
else
    docker compose up -d
fi
log "Docker stack up."

# ── Start Draw Things + proxy (if drawthings backend) ────────
if [ "$ENABLE_IMAGE_GENERATION" = "true" ] && [ "$IMAGE_GEN_BACKEND" = "drawthings" ]; then
    open -a "Draw Things" 2>/dev/null || log "Warning: Draw Things not found — install from App Store."

    PROXY_PID_FILE="$SCRIPT_DIR/logs/draw-things-proxy.pid"
    if [ -f "$PROXY_PID_FILE" ] && kill -0 "$(cat "$PROXY_PID_FILE")" 2>/dev/null; then
        log "Draw Things proxy already running (PID $(cat "$PROXY_PID_FILE"))."
    else
        DRAW_THINGS_URL="http://127.0.0.1:${DRAW_THINGS_PORT}" \
        DRAW_THINGS_PROXY_PORT="${DRAW_THINGS_PROXY_PORT}" \
        DRAW_THINGS_DEFAULT_MODEL="${DRAW_THINGS_DEFAULT_MODEL}" \
        nohup python3 "$SCRIPT_DIR/draw-things-proxy.py" \
            >> "$SCRIPT_DIR/logs/draw-things-proxy.log" 2>&1 &
        echo $! > "$PROXY_PID_FILE"
        log "Draw Things proxy started (PID $!) on port ${DRAW_THINGS_PROXY_PORT}."
    fi
fi

# ── Wait for WebUI to be healthy (up to 120 s) ───────────────
log "Waiting for WebUI..."
WEBUI_READY=false
for i in $(seq 1 60); do
    if curl -sf "http://localhost:${WEBUI_PORT}/health" >/dev/null 2>&1; then
        log "WebUI healthy."
        WEBUI_READY=true
        break
    fi
    sleep 2
done
if [ "$WEBUI_READY" = false ]; then
    log "Warning: WebUI not healthy after 120 s — skipping DB patch."
    exit 0
fi

# ── DB patch: ensure image engine settings ───────────────────
# Idempotent check — only patches when something is wrong/missing.
if [ "$ENABLE_IMAGE_GENERATION" = "true" ]; then
    for i in $(seq 1 15); do
        if docker exec open-webui test -f /app/backend/data/webui.db 2>/dev/null; then
            break
        fi
        sleep 1
    done

    if [ "$IMAGE_GEN_BACKEND" = "drawthings" ]; then
        NEEDS_PATCH=$(docker exec -i open-webui python3 - <<'PY' 2>/dev/null || echo "yes"
import sqlite3, json
row = sqlite3.connect('/app/backend/data/webui.db').cursor().execute(
    "SELECT data FROM config ORDER BY id DESC LIMIT 1").fetchone()
img = json.loads(row[0])['image_generation'] if row else {}
engine_ok = img.get('engine') == 'automatic1111'
size_ok = img.get('size') == '1024x1024'
url_ok = bool((img.get('automatic1111') or {}).get('base_url'))
openai_ok = not (img.get('openai') or {}).get('api_base_url')
print("no" if (engine_ok and size_ok and url_ok and openai_ok) else "yes")
PY
        )
        if [ "$NEEDS_PATCH" = "yes" ]; then
            log "Patching WebUI DB for Draw Things (automatic1111 engine)..."
            WEBUI_VOLUME="$(docker volume ls --format '{{.Name}}' | grep -E '_webui-data$' | head -n1)"
            docker compose kill open-webui >/dev/null 2>&1
            docker compose rm -f open-webui >/dev/null 2>&1
            docker run --rm -v "${WEBUI_VOLUME}:/data" python:3.12-alpine python -c "
import sqlite3, json
db = sqlite3.connect('/data/webui.db')
c = db.cursor()
row = c.execute('SELECT id, data FROM config ORDER BY id DESC LIMIT 1').fetchone()
cid, data = row[0], json.loads(row[1])
img = data.setdefault('image_generation', {})
img['engine'] = 'automatic1111'
img['size'] = '1024x1024'
img['openai'] = {}
img.setdefault('automatic1111', {})['base_url'] = 'http://host.docker.internal:${DRAW_THINGS_PROXY_PORT}'
c.execute('UPDATE config SET data=? WHERE id=?', (json.dumps(data), cid))
db.commit()
" && log "DB patch applied." || log "Warning: DB patch failed — check manually."
            docker compose up -d open-webui >/dev/null 2>&1
            for i in $(seq 1 30); do
                if curl -sf "http://localhost:${WEBUI_PORT}/health" >/dev/null 2>&1; then
                    break
                fi
                sleep 1
            done
        else
            log "DB already patched — nothing to do."
        fi
    else
        # comfyui: same FLUX.1-dev GGUF workflow as start.sh — keep in sync.
        NEEDS_PATCH=$(docker exec -i open-webui python3 - <<'PY' 2>/dev/null || echo "yes"
import sqlite3, json
row = sqlite3.connect('/app/backend/data/webui.db').cursor().execute(
    "SELECT data FROM config ORDER BY id DESC LIMIT 1").fetchone()
img = json.loads(row[0])['image_generation'] if row else {}
nodes_ok = any(n.get('key') == 'unet_name' for n in img.get('comfyui', {}).get('nodes', []))
size_ok = img.get('size') == '1024x1024'
engine_ok = (img.get('engine') or 'comfyui') == 'comfyui'
model_ok = img.get('model') == 'flux1-dev-Q4_K_S.gguf'
openai_ok = not (img.get('openai') or {}).get('api_base_url')
try:
    wf = json.loads(img.get('comfyui', {}).get('workflow') or '{}')
    workflow_ok = wf.get('4', {}).get('class_type') == 'UnetLoaderGGUF'
except Exception:
    workflow_ok = False
print("no" if (nodes_ok and size_ok and engine_ok and model_ok and openai_ok and workflow_ok) else "yes")
PY
        )
        if [ "$NEEDS_PATCH" = "yes" ]; then
            log "Patching WebUI DB (ComfyUI FLUX workflow + image settings)..."
            WEBUI_VOLUME="$(docker volume ls --format '{{.Name}}' | grep -E '_webui-data$' | head -n1)"
            docker compose kill open-webui >/dev/null 2>&1
            docker compose rm -f open-webui >/dev/null 2>&1
            docker run --rm -v "${WEBUI_VOLUME}:/data" python:3.12-alpine python -c "
import sqlite3, json
FLUX_WORKFLOW = {
    '3':  {'class_type': 'KSampler', 'inputs': {
        'seed': 0, 'steps': 20, 'cfg': 1.0,
        'sampler_name': 'euler', 'scheduler': 'simple', 'denoise': 1.0,
        'model': ['4', 0], 'positive': ['12', 0], 'negative': ['7', 0],
        'latent_image': ['5', 0],
    }},
    '4':  {'class_type': 'UnetLoaderGGUF',     'inputs': {'unet_name': 'flux1-dev-Q4_K_S.gguf'}},
    '5':  {'class_type': 'EmptySD3LatentImage','inputs': {'width': 1024, 'height': 1024, 'batch_size': 1}},
    '6':  {'class_type': 'CLIPTextEncode',     'inputs': {'text': '', 'clip': ['11', 0]}},
    '7':  {'class_type': 'CLIPTextEncode',     'inputs': {'text': '', 'clip': ['11', 0]}},
    '8':  {'class_type': 'VAEDecode',          'inputs': {'samples': ['3', 0], 'vae': ['10', 0]}},
    '9':  {'class_type': 'SaveImage',          'inputs': {'filename_prefix': 'Flux', 'images': ['8', 0]}},
    '10': {'class_type': 'VAELoader',          'inputs': {'vae_name': 'ae.safetensors'}},
    '11': {'class_type': 'DualCLIPLoader',     'inputs': {
        'clip_name1': 't5xxl_fp8_e4m3fn.safetensors',
        'clip_name2': 'clip_l.safetensors',
        'type': 'flux',
    }},
    '12': {'class_type': 'FluxGuidance',       'inputs': {'conditioning': ['6', 0], 'guidance': 3.5}},
}
db = sqlite3.connect('/data/webui.db')
c = db.cursor()
row = c.execute('SELECT id, data FROM config ORDER BY id DESC LIMIT 1').fetchone()
cid, data = row[0], json.loads(row[1])
img = data.setdefault('image_generation', {})
img['engine'] = 'comfyui'
img['model'] = 'flux1-dev-Q4_K_S.gguf'
img['size'] = '1024x1024'
img['steps'] = 20
img['openai'] = {}
cfg = img.setdefault('comfyui', {})
cfg['workflow'] = json.dumps(FLUX_WORKFLOW)
cfg['nodes'] = [
    {'type': 'prompt',   'key': 'text',       'node_ids': ['6']},
    {'type': 'model',    'key': 'unet_name',  'node_ids': ['4']},
    {'type': 'width',    'key': 'width',      'node_ids': ['5']},
    {'type': 'height',   'key': 'height',     'node_ids': ['5']},
    {'type': 'steps',    'key': 'steps',      'node_ids': ['3']},
    {'type': 'seed',     'key': 'seed',       'node_ids': ['3']},
]
c.execute('UPDATE config SET data=? WHERE id=?', (json.dumps(data), cid))
db.commit()
" && log "DB patch applied." || log "Warning: DB patch failed — check manually."
            docker compose up -d open-webui >/dev/null 2>&1
            for i in $(seq 1 30); do
                if curl -sf "http://localhost:${WEBUI_PORT}/health" >/dev/null 2>&1; then
                    break
                fi
                sleep 1
            done
        else
            log "DB already patched — nothing to do."
        fi
    fi
fi

# ── ComfyUI warmup: pre-load FLUX so first request is fast ──
if [ "$ENABLE_IMAGE_GENERATION" = "true" ] && [ "$IMAGE_GEN_BACKEND" = "comfyui" ] && \
   curl -sf "http://127.0.0.1:${COMFYUI_PORT}/system_stats" >/dev/null 2>&1; then
    if curl -sf "http://127.0.0.1:${COMFYUI_PORT}/prompt" \
            -H "Content-Type: application/json" \
            --data-binary @- >/dev/null 2>&1 <<'EOF'
{"prompt":{"3":{"class_type":"KSampler","inputs":{"seed":1,"steps":1,"cfg":1.0,"sampler_name":"euler","scheduler":"simple","denoise":1.0,"model":["4",0],"positive":["12",0],"negative":["7",0],"latent_image":["5",0]}},"4":{"class_type":"UnetLoaderGGUF","inputs":{"unet_name":"flux1-dev-Q4_K_S.gguf"}},"5":{"class_type":"EmptySD3LatentImage","inputs":{"width":256,"height":256,"batch_size":1}},"6":{"class_type":"CLIPTextEncode","inputs":{"text":"warmup","clip":["11",0]}},"7":{"class_type":"CLIPTextEncode","inputs":{"text":"","clip":["11",0]}},"8":{"class_type":"VAEDecode","inputs":{"samples":["3",0],"vae":["10",0]}},"9":{"class_type":"SaveImage","inputs":{"filename_prefix":"warmup","images":["8",0]}},"10":{"class_type":"VAELoader","inputs":{"vae_name":"ae.safetensors"}},"11":{"class_type":"DualCLIPLoader","inputs":{"clip_name1":"t5xxl_fp8_e4m3fn.safetensors","clip_name2":"clip_l.safetensors","type":"flux"}},"12":{"class_type":"FluxGuidance","inputs":{"conditioning":["6",0],"guidance":3.5}}}}
EOF
    then
        log "ComfyUI warmup queued (FLUX)."
    else
        log "Warning: ComfyUI warmup failed — first image request may be slow."
    fi
fi

log "=== boot-stack done ==="
