#!/usr/bin/env bash
#
# start.sh — Start the local AI stack
#
# What this does:
#   1. Copies .env.example to .env if you haven't created one yet
#   2. Reads your settings from .env (including OLLAMA_MODE)
#   3. Native mode: ensures Ollama is installed and running on your host
#   4. Docker mode: starts Ollama in an isolated container (no internet)
#   5. Wires optional bind mounts (shared folder, SSH keys, git config)
#   6. Ensures all models from models.conf are downloaded
#   7. Starts all containers
#
# Modes (set OLLAMA_MODE in .env):
#   "native"  = Ollama runs on your Mac with GPU acceleration (fast!)
#   "docker"  = Ollama runs in Docker, CPU-only but fully isolated
#
# Usage:
#   ./start.sh
#
# This is the only command you need. It handles everything:
#   - First run: downloads models, builds containers, starts the stack
#   - Subsequent runs: skips already-downloaded models, starts quickly
#   - Offline: works fine if models were previously downloaded
#   - After .env changes: picks up new settings automatically
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

# ── Detect platform ─────────────────────────────────────────
OS="$(uname -s)"
ARCH="$(uname -m)"

case "$OS" in
    Darwin)
        case "$ARCH" in
            arm64) PLATFORM="macOS (Apple Silicon)" ;;
            *)     PLATFORM="macOS (Intel)" ;;
        esac
        ;;
    Linux)
        if command -v nvidia-smi > /dev/null 2>&1; then
            PLATFORM="Linux ($ARCH, NVIDIA GPU)"
        else
            PLATFORM="Linux ($ARCH)"
        fi
        ;;
    *)
        PLATFORM="$OS ($ARCH)"
        ;;
esac

# ── Step 1: Ensure .env exists ──────────────────────────────
if [ ! -f .env ]; then
    echo "No .env found — copying from .env.example"
    cp .env.example .env
fi

# Load settings
set -a
source .env
set +a

OLLAMA_MODE="${OLLAMA_MODE:-native}"

echo "Platform: $PLATFORM"
echo "Ollama:   $OLLAMA_MODE mode"

case "$OLLAMA_MODE" in
    native)
        echo "          Ollama runs on your host with GPU acceleration."
        echo "          Open WebUI and Caddy run in Docker; ComfyUI runs natively."
        ;;
    docker)
        echo "          Everything runs in Docker. CPU-only but fully isolated."
        ;;
    *)
        echo "Error: OLLAMA_MODE must be 'native' or 'docker' (got: $OLLAMA_MODE)"
        exit 1
        ;;
esac
echo ""

# ── Step 2: Native mode — ensure Ollama is running ──────────
if [ "$OLLAMA_MODE" = "native" ]; then
    if ! command -v ollama > /dev/null 2>&1; then
        echo "Error: Ollama is not installed on your system."
        echo ""
        echo "Install it from: https://ollama.com/download"
        echo "Or switch to docker mode: set OLLAMA_MODE=docker in .env"
        exit 1
    fi

    # Check if Ollama is responding
    if ! ollama list > /dev/null 2>&1; then
        echo "Ollama is not running. Starting it..."
        if [ "$OS" = "Darwin" ]; then
            open -a Ollama 2>/dev/null || true
        else
            ollama serve > /dev/null 2>&1 &
        fi
        # Wait for it to be ready
        for i in $(seq 1 20); do
            if ollama list > /dev/null 2>&1; then
                break
            fi
            if [ "$i" -eq 20 ]; then
                echo "Error: Ollama failed to start. Please start it manually."
                exit 1
            fi
            sleep 1
        done
    fi
    echo "Ollama is running on your host."
    echo ""
fi

# ── Step 3: Generate docker-compose.override.yml ─────────────
# This file configures mode-specific settings and optional bind mounts.
# Docker Compose automatically merges it with docker-compose.yml.
OVERRIDE="docker-compose.override.yml"

ENABLE_IMAGE_GENERATION="${ENABLE_IMAGE_GENERATION:-true}"
COMFYUI_PORT="${COMFYUI_PORT:-8188}"

{
    echo "# Auto-generated by start.sh — do not edit manually"
    echo "services:"

    # ── open-webui overrides ──
    echo "  open-webui:"
    if [ "$OLLAMA_MODE" = "docker" ]; then
        echo "    depends_on:"
        echo "      ollama:"
        echo "        condition: service_healthy"
        echo "    environment:"
    else
        echo "    environment:"
        echo "      - OLLAMA_BASE_URL=http://host.docker.internal:11434"
    fi
    if [ "$ENABLE_IMAGE_GENERATION" = "true" ]; then
        echo "      - ENABLE_IMAGE_GENERATION=true"
        echo "      - IMAGE_GENERATION_ENGINE=comfyui"
        echo "      - COMFYUI_BASE_URL=http://host.docker.internal:${COMFYUI_PORT}"
        echo "      - IMAGES_EDIT_COMFYUI_BASE_URL=http://host.docker.internal:${COMFYUI_PORT}"
    fi

    # ── ollama-proxy overrides (docker mode only) ──
    if [ "$OLLAMA_MODE" = "docker" ]; then
        echo "  ollama-proxy:"
        echo "    depends_on:"
        echo "      ollama:"
        echo "        condition: service_healthy"
    fi
} > "$OVERRIDE"

echo "Generated $OVERRIDE"

# ── Step 4: Ensure TLS certs exist (mkcert) ──────────────────
CERT_DIR="certs"
CERT_FILE="$CERT_DIR/cert.pem"
KEY_FILE="$CERT_DIR/key.pem"

if [ ! -f "$CERT_FILE" ] || [ ! -f "$KEY_FILE" ]; then
    echo ""
    echo "Generating TLS certificates with mkcert..."

    if ! command -v mkcert > /dev/null 2>&1; then
        echo ""
        echo "Error: mkcert is not installed. Install it with:"
        echo "  brew install mkcert"
        echo "  mkcert -install"
        echo ""
        echo "Then re-run ./start.sh"
        exit 1
    fi

    # Detect LAN IP (first non-loopback IPv4)
    LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"

    mkdir -p "$CERT_DIR"
    mkcert -cert-file "$CERT_FILE" -key-file "$KEY_FILE" \
        localhost 127.0.0.1 ::1 ai.local ${LAN_IP:+"$LAN_IP"}
    echo "Certificates written to $CERT_DIR/"
    echo ""
    echo "To trust this cert on other LAN devices, install the mkcert CA:"
    echo "  CA file: $(mkcert -CAROOT)/rootCA.pem"
    echo "  iOS/Android: AirDrop or email the CA file, then trust it in Settings"
    echo "  Windows:     Import into 'Trusted Root Certification Authorities'"
    echo "  Linux:       Add to /usr/local/share/ca-certificates/ and run update-ca-certificates"
fi

# ── Step 5: Ensure models are downloaded ──────────────────────
if [ "$OLLAMA_MODE" = "docker" ]; then
    # Stop Ollama if it's running from a previous start — two Ollama
    # processes on the same data volume can cause corruption.
    docker compose --profile docker stop ollama 2>/dev/null || true
fi

echo ""
echo "Checking AI models..."
if ./pull-models.sh; then
    echo ""
else
    echo ""
    echo "Note: Could not pull models. If you're offline and models were"
    echo "previously downloaded, they'll still work. Otherwise, get online"
    echo "and run ./start.sh again."
    echo ""
fi

# ── Step 6: Start ComfyUI natively (image generation) ────────
if [ "$ENABLE_IMAGE_GENERATION" = "true" ] && [ -x "./start-comfyui.sh" ]; then
    echo ""
    ./start-comfyui.sh || echo "Warning: ComfyUI failed to start — Open WebUI will run without image generation."
fi

# ── Step 7: Start the stack ───────────────────────────────────
echo ""
echo "Starting local AI stack..."
if [ "$OLLAMA_MODE" = "docker" ]; then
    docker compose --profile docker up -d --build
else
    docker compose up -d --build
fi

echo ""
echo "Stack is up. Services:"
docker compose ps
echo ""
LAN_IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)"
if [ "${WEBUI_SSL_PORT:-443}" = "443" ]; then
    echo "Open WebUI: https://localhost  (this machine)"
    echo "            https://ai.local   (LAN — mDNS)${LAN_IP:+", https://$LAN_IP  (LAN — IP)"}"
else
    echo "Open WebUI: https://localhost:${WEBUI_SSL_PORT}  (this machine)"
    echo "            https://ai.local:${WEBUI_SSL_PORT}   (LAN — mDNS)"
fi
echo "            http://localhost:${WEBUI_PORT:-3000}  (HTTP fallback)"
if [ "$OLLAMA_MODE" = "native" ]; then
    echo "Ollama:     running natively on your host (localhost:11434)"
fi
if [ "$ENABLE_IMAGE_GENERATION" = "true" ]; then
    echo "ComfyUI:    running natively on your host (localhost:${COMFYUI_PORT})"
fi
